apiVersion: v1
kind: ServiceAccount
metadata:
  name: bellboy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bellboy
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bellboy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bellboy
subjects:
- kind: ServiceAccount
  name: bellboy
  namespace: default
